version: "3"
services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             export DJANGO_SUPERUSER_EMAIL=test@test.com
             export DJANGO_SUPERUSER_PASSWORD=testpass1234
             python manage.py createsuperuser --no-input
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=somesupersecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=changeme
      - ALLOWED_HOSTS=188.245.47.197,0.0.0.0
    depends_on:
      - db
  db:
    image: postgres:15-alpine3.18
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme