# Generated by Django 4.2.4 on 2023-08-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_basemodel_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='image',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
